<?php

namespace HWafeq\LaravelWafeq\Data;

use Spatie\LaravelData\Data;

/**
 * @property string $id
 * @property ?string $amount
 * @property ?string $amountToBcy
 * @property ?string $balance
 * @property ?string $date
 * @property ?string $description
 * @property ?string $journal
 * @property ?string $legacyId
 * @property array<string, mixed> $extra
 *
 * Recognised-amortization entry embedded inside an [AmortizationData](../dtos.md).
 * Mirrors the Wafeq `AmortizationEvent` schema returned on
 * `Amortization.events`. Read-only — generated by the amortization
 * schedule, never created directly.
 *
 * @see LaravelWafeq
 */
class AmortizationEventData extends Data
{
    /**
     * @param  array<string, mixed>  $extra
     */
    public function __construct(
        public string $id = '',
        public ?string $amount = null,
        public ?string $amountToBcy = null,
        public ?string $balance = null,
        public ?string $date = null,
        public ?string $description = null,
        public ?string $journal = null,
        public ?string $legacyId = null,
        public array $extra = [],
    ) {}
}
